

services:
  network-device:
    image: network_device
    container_name: dne
    build:
      context: ./network_device
    expose:
      - 22
      - 830

  netconf-api:
    image: netconf_api
    container_name: api
    build:
      context: ./api
    expose:
      - 5000
      - 22

  httpd:
    image: dne_nginx
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - netconf_api